version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - BASE_URL=http://localhost:3000
      - MONGODB_URI=mongodb+srv://stream:telvinteum@stream.o3qip.mongodb.net/?retryWrites=true&w=majority&appName=stream
      - SESSION_SECRET=KquWbFL6DYB7sw4FxuVXAyZnwbfArT0YpoxF1yNGKZg
      - JWT_SECRET=iYYO8jSXNZauzM7tNKcyQMZhJhwIG-_XcFDwf5OIfgk
      - UPLOAD_DIR=uploads
      - MAX_FILE_SIZE=20000000
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=teumteum776@gmail.com
      - SMTP_PASS=lxnqofjkeeivvjqq
      - MAX_VIDEO_SIZE=20000000
      - MAX_THUMBNAIL_SIZE=20000000
      - ALLOWED_VIDEO_TYPES=video/mp4,video/webm
      - ALLOWED_IMAGE_TYPES=image/jpeg,image/png,image/gif
      - UPLOAD_PATH=/app/public/uploads
      - TEMP_PATH=/app/uploads/temp
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./uploads/temp:/app/uploads/temp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge